package com.gzych.sipesb.objects.model;

// default package
// Generated 2016-05-23 09:20:19 by Hibernate Tools 3.6.0

/**
 * EpDanePodmiotu generated by hbm2java
 */
@SuppressWarnings("serial")
public class EpDanePodmiotu implements java.io.Serializable {

	private long dapoId;
	private EpMetadaneDokumentu epMetadaneDokumentu;
	private String dapoIdentyfikator;
	private String dapoTypOsoby;
	private String dapoImieSkrot;
	private String dapoNazwiskoNazwa;
	private String dapoNip;
	private String dapoPesel;
	private String dapoRegon;
	private Boolean dapoZgoda;
	private String dapoUUID;

	public EpDanePodmiotu() {
	}

	public EpDanePodmiotu(long dapoId) {
		this.dapoId = dapoId;
	}

	public EpDanePodmiotu(long dapoId, EpMetadaneDokumentu epMetadaneDokumentu, String dapoIdentyfikator,
			String dapoTypOsoby, String dapoImieSkrot, String dapoNazwiskoNazwa, String dapoNip, String dapoPesel,
			String dapoRegon, Boolean dapoZgoda, String dapoUUID) {
		this.dapoId = dapoId;
		this.epMetadaneDokumentu = epMetadaneDokumentu;
		this.dapoIdentyfikator = dapoIdentyfikator;
		this.dapoTypOsoby = dapoTypOsoby;
		this.dapoImieSkrot = dapoImieSkrot;
		this.dapoNazwiskoNazwa = dapoNazwiskoNazwa;
		this.dapoNip = dapoNip;
		this.dapoPesel = dapoPesel;
		this.dapoRegon = dapoRegon;
		this.dapoZgoda = dapoZgoda;
		this.dapoUUID = dapoUUID;
	}

	public long getDapoId() {
		return this.dapoId;
	}

	public void setDapoId(long dapoId) {
		this.dapoId = dapoId;
	}

	public EpMetadaneDokumentu getEpMetadaneDokumentu() {
		return this.epMetadaneDokumentu;
	}

	public void setEpMetadaneDokumentu(EpMetadaneDokumentu epMetadaneDokumentu) {
		this.epMetadaneDokumentu = epMetadaneDokumentu;
	}

	public String getDapoIdentyfikator() {
		return this.dapoIdentyfikator;
	}

	public void setDapoIdentyfikator(String dapoIdentyfikator) {
		this.dapoIdentyfikator = dapoIdentyfikator;
	}

	public String getDapoTypOsoby() {
		return this.dapoTypOsoby;
	}

	public void setDapoTypOsoby(String dapoTypOsoby) {
		this.dapoTypOsoby = dapoTypOsoby;
	}

	public String getDapoImieSkrot() {
		return this.dapoImieSkrot;
	}

	public void setDapoImieSkrot(String dapoImieSkrot) {
		this.dapoImieSkrot = dapoImieSkrot;
	}

	public String getDapoNazwiskoNazwa() {
		return this.dapoNazwiskoNazwa;
	}

	public void setDapoNazwiskoNazwa(String dapoNazwiskoNazwa) {
		this.dapoNazwiskoNazwa = dapoNazwiskoNazwa;
	}

	public String getDapoNip() {
		return this.dapoNip;
	}

	public void setDapoNip(String dapoNip) {
		this.dapoNip = dapoNip;
	}

	public String getDapoPesel() {
		return this.dapoPesel;
	}

	public void setDapoPesel(String dapoPesel) {
		this.dapoPesel = dapoPesel;
	}

	public String getDapoRegon() {
		return this.dapoRegon;
	}

	public void setDapoRegon(String dapoRegon) {
		this.dapoRegon = dapoRegon;
	}

	public Boolean getDapoZgoda() {
		return this.dapoZgoda;
	}

	public void setDapoZgoda(Boolean dapoZgoda) {
		this.dapoZgoda = dapoZgoda;
	}

	public String getDapoUUID() {
		return this.dapoUUID;
	}

	public void setDapoUUID(String dapoUUID) {
		this.dapoUUID = dapoUUID;
	}
}
