package com.gzych.sipesb.objects.model;
// default package
// Generated 2016-05-23 09:20:19 by Hibernate Tools 3.6.0

/**
 * EpDaneNadawcy generated by hbm2java
 */
@SuppressWarnings("serial")
public class EpDaneNadawcy implements java.io.Serializable {

	private long danaId;
	private EpMetadaneDokumentu epMetadaneDokumentu;
	private String danaUzytkownik;
	private String danaSystem;
	private String danaUUID;

	public EpDaneNadawcy() {
	}

	public EpDaneNadawcy(long danaId) {
		this.danaId = danaId;
	}

	public EpDaneNadawcy(long danaId, EpMetadaneDokumentu epMetadaneDokumentu, String danaUzytkownik,
			String danaSystem, String danaUUID) {
		this.danaId = danaId;
		this.epMetadaneDokumentu = epMetadaneDokumentu;
		this.danaUzytkownik = danaUzytkownik;
		this.danaSystem = danaSystem;
		this.danaUUID = danaUUID;
	}

	public long getDanaId() {
		return this.danaId;
	}

	public void setDanaId(long danaId) {
		this.danaId = danaId;
	}

	public EpMetadaneDokumentu getEpMetadaneDokumentu() {
		return this.epMetadaneDokumentu;
	}

	public void setEpMetadaneDokumentu(EpMetadaneDokumentu epMetadaneDokumentu) {
		this.epMetadaneDokumentu = epMetadaneDokumentu;
	}

	public String getDanaUzytkownik() {
		return this.danaUzytkownik;
	}

	public void setDanaUzytkownik(String danaUzytkownik) {
		this.danaUzytkownik = danaUzytkownik;
	}

	public String getDanaSystem() {
		return this.danaSystem;
	}

	public void setDanaSystem(String danaSystem) {
		this.danaSystem = danaSystem;
	}

	public String getDanaUUID() {
		return this.danaUUID;
	}

	public void setDanaUUID(String danaUUID) {
		this.danaUUID = danaUUID;
	}
}
