package com.gzych.sipesb.objects.model;

// default package
// Generated 2016-05-23 09:20:19 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.List;
import java.util.Set;

import com.gzych.sipesb.common.enums.TransakcjaStatus;

import javax.persistence.*;

/**
 * EpMetadaneDokumentu generated by hbm2java
 */
@SuppressWarnings("serial")
public class EpMetadaneDokumentu implements java.io.Serializable {

	private long medoId;
	private EpTransakcjaOdbioru epTransakcjaOdbioru;
	private EpTransakcjaWyslania epTransakcjaWyslania;
	private String medoNazwa;
	private TransakcjaStatus medoStatus;
	private Date medoDataNadania;
	private boolean medoCzyTestowe;
	private byte[] medoDaneDodatkowe;
	private Set<EpDokument> epDokuments;
	private Set<EpDaneNadawcy> epDaneNadawcies;
	private Set<EpDanePodmiotu> epDanePodmiotus;
	private Set<EpSkrytkaAdres> epSkrytkaAdreses;
	private String medoUUID;

	public EpMetadaneDokumentu() {
	}

	public EpMetadaneDokumentu(long medoId) {
		this.medoId = medoId;
	}

	public EpMetadaneDokumentu(long medoId, EpTransakcjaOdbioru epTransakcjaOdbioru,
			EpTransakcjaWyslania epTransakcjaWyslania, String medoNazwa, Date medoDataNadania, Boolean medoCzyTestowe,
			byte[] medoDaneDodatkowe, Set<EpDokument> epDokuments, Set<EpDaneNadawcy> epDaneNadawcies,
							   Set<EpDanePodmiotu> epDanePodmiotus, Set<EpSkrytkaAdres> epSkrytkaAdreses,String medoUUID) {
		this.medoId = medoId;
		this.epTransakcjaOdbioru = epTransakcjaOdbioru;
		this.epTransakcjaWyslania = epTransakcjaWyslania;
		this.medoNazwa = medoNazwa;
		this.medoDataNadania = medoDataNadania;
		this.medoCzyTestowe = medoCzyTestowe;
		this.medoDaneDodatkowe = medoDaneDodatkowe;
		this.epDokuments = epDokuments;
		this.epDaneNadawcies = epDaneNadawcies;
		this.epDanePodmiotus = epDanePodmiotus;
		this.epSkrytkaAdreses = epSkrytkaAdreses;
		this.medoUUID = medoUUID;
	}

	public long getMedoId() {
		return this.medoId;
	}

	public void setMedoId(long medoId) {
		this.medoId = medoId;
	}

	public EpTransakcjaOdbioru getEpTransakcjaOdbioru() {
		return this.epTransakcjaOdbioru;
	}

	public void setEpTransakcjaOdbioru(EpTransakcjaOdbioru epTransakcjaOdbioru) {
		this.epTransakcjaOdbioru = epTransakcjaOdbioru;
	}

	public EpTransakcjaWyslania getEpTransakcjaWyslania() {
		return this.epTransakcjaWyslania;
	}

	public void setEpTransakcjaWyslania(EpTransakcjaWyslania epTransakcjaWyslania) {
		this.epTransakcjaWyslania = epTransakcjaWyslania;
	}

	public String getMedoNazwa() {
		return this.medoNazwa;
	}

	public void setMedoNazwa(String medoNazwa) {
		this.medoNazwa = medoNazwa;
	}

	public Date getMedoDataNadania() {
		return this.medoDataNadania;
	}

	public void setMedoDataNadania(Date medoDataNadania) {
		this.medoDataNadania = medoDataNadania;
	}

	public boolean getMedoCzyTestowe() {
		return this.medoCzyTestowe;
	}

	public void setMedoCzyTestowe(boolean medoCzyTestowe) {
		this.medoCzyTestowe = medoCzyTestowe;
	}

	public byte[] getMedoDaneDodatkowe() {
		return this.medoDaneDodatkowe;
	}

	public void setMedoDaneDodatkowe(byte[] medoDaneDodatkowe) {
		this.medoDaneDodatkowe = medoDaneDodatkowe;
	}

	public Set<EpDokument> getEpDokuments() {
		return this.epDokuments;
	}

	public void setEpDokuments(Set<EpDokument> epDokuments) {
		this.epDokuments = epDokuments;
	}

	public Set<EpDaneNadawcy> getEpDaneNadawcies() {
		return this.epDaneNadawcies;
	}

	public void setEpDaneNadawcies(Set<EpDaneNadawcy> epDaneNadawcies) {
		this.epDaneNadawcies = epDaneNadawcies;
	}

	public Set<EpDanePodmiotu> getEpDanePodmiotus() {
		return this.epDanePodmiotus;
	}

	public void setEpDanePodmiotus(Set<EpDanePodmiotu> epDanePodmiotus) {
		this.epDanePodmiotus = epDanePodmiotus;
	}

	public Set<EpSkrytkaAdres> getEpSkrytkaAdreses() {
		return this.epSkrytkaAdreses;
	}

	public void setEpSkrytkaAdreses(Set<EpSkrytkaAdres> epSkrytkaAdreses) {
		this.epSkrytkaAdreses = epSkrytkaAdreses;
	}

	public TransakcjaStatus getMedoStatus() {
		return medoStatus;
	}

	public void setMedoStatus(TransakcjaStatus medoStatus) {
		this.medoStatus = medoStatus;
	}

	public String getMedoUUID() {
		return this.medoUUID;
	}

	public void setMedoUUID(String medoUUID) {
		this.medoUUID = medoUUID;
	}
}
