package com.gzych.sipesb.objects.model;

import com.gzych.sipesb.common.enums.TypAdresSkrytki;

// default package
// Generated 2016-05-23 09:20:19 by Hibernate Tools 3.6.0

/**
 * EpSkrytkaAdres generated by hbm2java
 */
@SuppressWarnings("serial")
public class EpSkrytkaAdres implements java.io.Serializable {

	private long skadId;
	private EpMetadaneDokumentu epMetadaneDokumentu;
	private String skadTyp;
	private String skadNazwaSkrytki;
	private String skadAdresSkrytki;
	private String skadUUID;

	public EpSkrytkaAdres() {
	}

	public EpSkrytkaAdres(long skadId) {
		this.skadId = skadId;
	}

	public EpSkrytkaAdres(long skadId, EpMetadaneDokumentu epMetadaneDokumentu, String skadTyp, String skadNazwaSkrytki,
			String skadAdresSkrytki, String skadUUID) {
		this.skadId = skadId;
		this.epMetadaneDokumentu = epMetadaneDokumentu;
		this.skadTyp = skadTyp;
		this.skadNazwaSkrytki = skadNazwaSkrytki;
		this.skadAdresSkrytki = skadAdresSkrytki;
		this.skadUUID = skadUUID;
	}

	public long getSkadId() {
		return this.skadId;
	}

	public void setSkadId(long skadId) {
		this.skadId = skadId;
	}

	public EpMetadaneDokumentu getEpMetadaneDokumentu() {
		return this.epMetadaneDokumentu;
	}

	public void setEpMetadaneDokumentu(EpMetadaneDokumentu epMetadaneDokumentu) {
		this.epMetadaneDokumentu = epMetadaneDokumentu;
	}

	public String getSkadTyp() {
		return this.skadTyp;
	}

	public void setSkadTyp(String skadTyp) {
		this.skadTyp = skadTyp;
	}

	public String getSkadNazwaSkrytki() {
		return this.skadNazwaSkrytki;
	}

	public void setSkadNazwaSkrytki(String skadNazwaSkrytki) {
		this.skadNazwaSkrytki = skadNazwaSkrytki;
	}

	public String getSkadAdresSkrytki() {
		return this.skadAdresSkrytki;
	}

	public void setSkadAdresSkrytki(String skadAdresSkrytki) {
		this.skadAdresSkrytki = skadAdresSkrytki;
	}

	public String getSkadUUID() {
		return this.skadUUID;
	}

	public void setSkadUUID(String skadUUID) {
		this.skadUUID = skadUUID;
	}
}
