package com.gzych.sipesb.objects.model;

// default package
// Generated 2016-05-23 09:20:19 by Hibernate Tools 3.6.0

import javax.persistence.*;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * EpTransakcjaWyslania generated by hbm2java
 */
@SuppressWarnings("serial")
public class EpTransakcjaWyslania implements java.io.Serializable {

	private long trwyId;
	private Date trwyDataZalozenia;
	private String trwyStatus;
	private String trwyLogin;
	private Set<EpMetadaneDokumentu> epMetadaneDokumentus;
	private String trwyUUID;

	public EpTransakcjaWyslania() {	}
	public EpTransakcjaWyslania(long trwyId) {
		this.trwyId = trwyId;
	}
	public EpTransakcjaWyslania(long trwyId, Date trwyDataZalozenia, String trwyStatus, String trwyLogin,
								Set<EpMetadaneDokumentu> epMetadaneDokumentus, String trwyUUID) {
		this.trwyId = trwyId;
		this.trwyDataZalozenia = trwyDataZalozenia;
		this.trwyStatus = trwyStatus;
		this.trwyLogin = trwyLogin;
		this.epMetadaneDokumentus = epMetadaneDokumentus;
		this.trwyUUID = trwyUUID;
	}

	public long getTrwyId() {
		return this.trwyId;
	}

	public void setTrwyId(long trwyId) {
		this.trwyId = trwyId;
	}

	public Date getTrwyDataZalozenia() {
		return this.trwyDataZalozenia;
	}

	public void setTrwyDataZalozenia(Date trwyDataZalozenia) {
		this.trwyDataZalozenia = trwyDataZalozenia;
	}

	public String getTrwyStatus() {
		return this.trwyStatus;
	}

	public void setTrwyStatus(String trwyStatus) {
		this.trwyStatus = trwyStatus;
	}

	public String getTrwyLogin() {
		return this.trwyLogin;
	}

	public void setTrwyLogin(String trwyLogin) {
		this.trwyLogin = trwyLogin;
	}

	public Set<EpMetadaneDokumentu> getEpMetadaneDokumentus() {
		return this.epMetadaneDokumentus;
	}

	public void setEpMetadaneDokumentus(Set<EpMetadaneDokumentu> epMetadaneDokumentus) {
		this.epMetadaneDokumentus = epMetadaneDokumentus;
	}

	public String getTrwyUUID() {
		return this.trwyUUID;
	}

	public void setTrwyUUID(String trwyUUID) {
		this.trwyUUID = trwyUUID;
	}

}
